### ISSUE TITLE
[Proposal] Refactor liget.sh and the docker container composition.

### ISSUE THREAD

**Issue by ElanHasson** [ai-traders/liget#5]
I'd like to propose removing liget.sh and refactoring the config file generation to be done outside of the image, such as by mounting a filesystem for the configuration.

By separating out this behavior, it will enable more flexibility and customization with regard to the configurations allowed.

For my specific use case, I'll be deploying on kubernetes via helm and would prefer to be able to read configs from a ConfigMap mounted as a file.

I'll also be putting together a helm chart which will support easy deployment on kubernetes.

I'd also like to switch the container from ubuntu based to alpine for a smaller image. Part of this work would be to follow the best practices laid out by the dotnet core team for building and making the images: https://github.com/dotnet/dotnet-docker/blob/master/samples/dotnetapp/Dockerfile.alpine-x64

Any thoughts on this?

**Comment by tomzo** [comment]
Hi,

You can avoid config generation by setting `LIGET_LOG_BACKEND=custom` and then mounting `/etc/liget/log4net.xml`.
We are deploying on k8s too, but we use environment variables to configure everything.

I think switch to alpine is possible. But please note, for the last few days I have been on working on [BaGet fork](https://github.com/ai-traders/baget) and moving V2 from LiGet to BaGet. My intentions are to make a BaGet image which is a drop-in replacement for LiGet.
It would be faster and implement both V2 and V3 though.

**Comment by ElanHasson** [comment]
Looks good. I will switch to your BaGet fork. I've got a helm chart I put together last night for liget I'll send a PR for.

**Comment by ElanHasson** [comment]
I just took a look at the upstream BaGet repo and I'm a bit apprehensive based on a cursory code review and looking at the upstream issue log. The lack of test coverage is also a concern for me.

Per the upstream docs, they state it's hard to scale the writes.

I'm using nuget packages as a dependency storage and delivery mechanism in a high volume, dynamic system that relies heavily on NuGet packages at task runtime.

My concern is that this won't be able to scale to support my workload in a cost-effective manner.

What is your primary use case workload like?

**Comment by tomzo** [comment]
> The lack of test coverage is also a concern for me.

Yes, that's a big issue for me too. I have been adding tests on the way. Also ported some from LiGet. Upstream is really just a PoC, I have working make it acceptable for production for a few days now.
There is no open source V3 implementation that has sufficient tests, so I we just have to write them for all use cases needed.

> Performance concerns

I haven't measured anything in BaGet yet. I plan to add performance tests, profile the application and add metrics to send to influxdb+grafana for analysis. 
In my opinion BaGet is better base for building something fast than LiGet since we have made 3 mistakes in LiGet which affect performance:
 - nancyfx is poor at handling async tasks properly
 - cache is implemented with dbreeze which is handling concurrent access with locks
 - core metadata storage of LiGet is using json file. That's just how NuGet.Server project did it and it is still here.

> What is your primary use case workload like?

We have up to ~15 CI agents building various dotnet projects. Each project is using ~200 packages (all dependencies including transitive) from nuget.org and a few private packages. So we want to use read-through cache to speed up downloads and queries for public packages. The biggest load is on the public packages.
In my fork I have separated the storage for private packages and public ones. So that database is not used at all when we query/download for public packages.
Currently queries go to upstream nuget.org, downloads are cached locally.
Later I will add caching of query responses too, in similar way I did in LiGet.

> I'm using nuget packages as a dependency storage and delivery mechanism in a high volume, dynamic system that relies heavily on NuGet packages at task runtime.

What's your ratio of public/private packages to be served?

**Comment by ElanHasson** [comment]
> nancyfx is poor at handling async tasks properly
Why use a custom router at all? What functionality is required that ASP.Net doesn't provide out of the box?

> cache is implemented with dbreeze which is handling concurrent access with locks
The concurrency needs should be handled by the underlying cache provider and would be coupled to the guarantees of the storage provider (ie: consistency levels). 

Cache and storage should be implemented via providers anyway, making it easy to swap out. The service should not know or care about *how* storage happens or what consistency guarantees are provided by the provider. The use case should dictate what to use, and the operator should have the ability to do this via configuration.

> What's your ratio of public/private packages to be served?
I've built a serverless platform that packages functions as nupkgs. When you create the function, it's built and packaged as a nuget, defining dependencies using nugets. The majority are public packages, but as more composition occurs on functions (shared libraries used by functions) they will grow. I think the usage of public packages will always be the greater usage of private packages.

I have on my roadmap to implement durable workflows by chaining functions together, which will increase private package consumption. I do not think the private/public mix is really relevant. 
You still need to deliver N packages. My understanding is when a nuget restore occurs, searches are not happening as the uri to download a nupkg file is deterministic (package name + version). This means it's 100% an HTTP GET problem in the simple scenario (private nuget repos are different, but many modern proxies can auth on top of cache). 

Of course, since packages are immutable, this means that they are highly-cacheable outside of the NuGet server. Perhaps the problem is better solved using existing proxy solutions.

Currently, each function runs in it's own sandboxed container and is disposed of after execution completes. Which means nupkgs are downloaded each time. I've considered leveraging the immutability characteristics of nuget packages and bundling the packages together in a PVC for mounting on the pod , offloading the "cache" to the underlying k8s storage provider.

**Comment by tomzo** [comment]
I have included your original suggestion in 1.0.0 release. There are [2 env variables](https://github.com/ai-traders/liget#configuration) which allow to skip config generation from env variables and just mount user-provided files.
I am done with BaGet work, the fork is now merged to LiGet. For more information see the current readme.
